### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by lupeterm** [kangjie-ding/Octree-based-Region-Growing#1]
Your code looks great! Kind of reminds me of  [someone elses](https://github.com/lupeterm/OBRG-Py/tree/main) though.

**Comment by kangjie-ding** [comment]
This is my carelessness. This work is based on [this work](https://github.com/lupeterm/OBRG-Py/tree/main), which is a great repository, and should be cited in my repository description. It reproduced the paper ideas quite well! We made some updates based on his code, such as flatness detection, refinement processes, and 26 neighbor voxel search algorithm, etc.

**Comment by lupeterm** [comment]
No hard feelings, and thanks!
